language: python
os:
  - linux
matrix:
  fast_finish: true
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      sudo: required
      dist: xenial
    - python: nightly
      sudo: required
      dist: xenial
  allow_failures:
    - python: nightly
# command to run tests
install: python setup.py develop
script: python setup.py test

